version: '3.8'

networks:
    default:
        name: adata-net
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: ${NETWORK_SUBNET}

services:

    php-fpm:
        build:
            context: ./services/php
            dockerfile: Dockerfile
        container_name: ${COMPOSE_APP_NAME}-php-fpm
        restart: always
        tty: true
        working_dir: /var/www/${COMPOSE_APP_NAME}
        volumes:
            - ${APP_PATH}/:/var/www/${COMPOSE_APP_NAME}
            - ./docker/services/php/config/php.ini:/usr/local/etc/php/conf.d/php.ini

    nginx:
        build:
            context: ./services/nginx
            dockerfile: Dockerfile
        container_name: ${COMPOSE_APP_NAME}-nginx
        restart: always
        tty: true
        ports:
            - ${APP_PORT_MAP}
        working_dir: /var/www
        volumes:
            - ${APP_PATH}/:/var/www/${COMPOSE_APP_NAME}
